#pragma once

#include <ka/exact/GridParameters.hpp>
#include <ka/exact/GridRounding.hpp>

namespace ka
{

/// This values are autogenerated.
constexpr GridParameters g_embedded_grid = {
    .cell_size = 0x2.637f08ae147aep-8,
    .desired_cell_size = 0x2.637f08ae147aep-8,
    .min_input = 0xa.3d70a3d70a3d8p-11,
    .max_input = 0x8p+22,
    .column_border_intersecion = {
        .min_reliable_fractional_part = 0x8.caa30eff9808p-20,
        .max_reliable_fractional_part = 0xf.fff7355cf1p-4,
    },
};

template <GridRounding rounding>
[[nodiscard]] TileCellGrid<rounding> make_grid(const f64 cell_size, const u16 tile_step)
{
    auto grid = g_embedded_grid;
    grid.cell_size = cell_size;
    return { grid, tile_step };
}

} // namespace ka
