/// This file is generated by 
/// Don't edit it manually.

#pragma once

#include <common/fixed.hpp>

namespace r7
{

/// Minimal allowed absolute value of input coordinates.
constexpr f64 g_min_regular_grid_input_coordinate = 0x8p-4;

/// Maximal allowed absolute value of input coordinates.
constexpr f64 g_max_regular_grid_input_coordinate = 0x8p+29;

/// Minimal allowed step of the regular grid.
constexpr f64 g_min_grid_step = 0xe.edd9f64p-4;

namespace column_border_intersecion_detail
{

/// Smaller values of the fractional part do not guarantee correct rounding in the column_border_intersecion.
constexpr f64 g_min_reliable_fractional_part = 0xb.40d0b709b85cp-20;

/// Larger values of the fractional part do not guarantee correct rounding in the column_border_intersecion.
constexpr f64 g_max_reliable_fractional_part = 0xf.fff4bf2f48f6p-4;

} // namespace column_border_intersecion_detail

} // namespace r7
