/// This file is autogenerated. Don't edit it manually.

#pragma once

#include <ka/exact/GridParameters.hpp>

namespace ka
{

constexpr GridParameters g_embedded_grid = {
    .cell_size = 0x2.637f08ae147aep-8,
    .desired_cell_size = 0x2.637f08ae147aep-8,
    .min_input = 0xa.3d70a3d70a3d8p-11,
    .max_input = 0x8p+22,
    .column_border_intersecion = {
        .min_reliable_fractional_part = 0x8.caa30eff9808p-20,
        .max_reliable_fractional_part = 0xf.fff7355cf1p-4,
    },
};

} // namespace ka::test
