name: 🔨 Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conf:
          - id: ubuntu-clang-18-libstdc++11
            runner: ubuntu-latest
            conan-profile: |
              [settings]
              arch=x86_64
              os=Linux
              compiler=clang
              compiler.cppstd=20
              compiler.libcxx=libstdc++11
              compiler.version=18
              build_type=Release

              [conf]
              tools.build:compiler_executables={"c": "clang-18", "cpp": "clang++-18"}

          - id: ubuntu-gcc-14-libstdc++11
            runner: ubuntu-latest
            conan-profile: |
              [settings]
              arch=x86_64
              os=Linux
              compiler=gcc
              compiler.cppstd=20
              compiler.libcxx=libstdc++11
              compiler.version=14
              build_type=Release

              [conf]
              tools.build:compiler_executables={"c": "gcc-14", "cpp": "g++-14"}

          - id: macos-apple-clang-16-libc++
            runner: macos-15
            conan-profile: |
              [settings]
              arch=armv8
              os=Macos
              compiler=apple-clang
              compiler.cppstd=20
              compiler.libcxx=libc++
              compiler.version=16
              build_type=Release

              [conf]
              tools.build:compiler_executables={"c": "clang", "cpp": "clang++"}

          - id: windows-msvc-2022
            runner: windows-latest
            conan-profile: |
              [settings]
              arch=x86_64
              os=Windows
              compiler=msvc
              compiler.cppstd=20
              compiler.version=194
              compiler.runtime=static
              compiler.runtime_type=Release
              build_type=Release

    runs-on: ${{ matrix.conf.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install conan 2
        run: pip install "conan~=2.0"

      # Loading cache to drive C: is extremly slow on windows.
      # https://github.com/actions/setup-go/issues/495
      # https://github.com/actions/setup-go/pull/515
      - name: Set CONAN_HOME (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: echo CONAN_HOME=D:/conan >> "$env:GITHUB_ENV"
      - name: Set CONAN_HOME
        if: ${{ runner.os != 'Windows' }}
        run: echo CONAN_HOME=~/.conan2 >> "$GITHUB_ENV"

      - name: Create conan profile
        run: |
          mkdir -p ${{ env.CONAN_HOME }}/profiles
          echo '${{ matrix.conf.conan-profile }}' > ${{ env.CONAN_HOME }}/profiles/default

      - name: Restore conan cache
        id: restore-conan-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CONAN_HOME }}/p
          key: ${{ matrix.conf.id }}

      - name: Install dependencies
        run: conan install . --build missing

      - name: Save conan cache
        if: steps.restore-conan-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CONAN_HOME }}/p
          key: ${{ matrix.conf.id }}

      - name: Run conan create
        run: conan create .
